### PR TITLE
Add logos and make logos.json point to their internal paths

### PR DESCRIPTION
**Pull request by aredridel**
BREAKING CHANGE: logo data is now relative to package root not an absolute URL

### CODE REVIEW

**Comment by aredridel** [comment]
@bcoe would love your thoughts on this approach. This gets us not depending on cloudup and (raw)github for our front page, and we can use our own CDN for this.

**Comment by bcoe** [comment]
@aredridel I remember discussing this a while back, did you ultimately opt for another approach for logos?

**Comment by bcoe** [comment]
@aredridel bump, don't want to close this out without confirming we don't need it 👍

**Comment by aredridel** [comment]
Might as well close it, @bcoe

**Pull request closed without merging**
